
FROM openjdk:17-oracle
ARG JAR_FILE=target/*.war
COPY ${JAR_FILE} cubeDemo.war
ARG WEB_PASSWORD
ENV WEB_PASSWORD=${WEB_PASSWORD}
ARG MONGO_URI
ENV MONGO_URI=${MONGO_URI}
ARG MONGO_DATABASE
ENV MONGO_DATABASE=${MONGO_DATABASE}
ENTRYPOINT ["java","-jar","/cubeDemo.war"]
EXPOSE 8080

